FROM ubuntu:20.04
WORKDIR /workspace

ENV PATH="/home/bayes_classifie/.local/bin:$PATH"
RUN apt update
RUN apt install python3 python3-pip -y
COPY requirements.migration.txt requirements.txt
RUN pip install --disable-pip-version-check -r requirements.txt

COPY . .
CMD ["/bin/bash", "./scripts/run_migration.sh"]